name: Test

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
          - os: macos-latest
          - os: ubuntu-24.04
            compiler: clang
          - os: ubuntu-latest
            compiler: gcc
    name: 🧪 Test on ${{ matrix.os }}${{case(matrix.compiler == '', '', format(' with {0}', matrix.compiler))}}
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: 🪟 Install LLVM and Clang
        uses: Nerixyz/install-llvm-action@9360934cdd190acb71725924f8d8ebd7a1acdf93
        if: runner.os == 'Windows'
        with:
          version: "22.1"

      - name: 🪟 🐛 Fix LLDB .pyd
        shell: powershell
        if: runner.os == 'Windows'
        run: |
          mv "C:\Program Files\LLVM\Lib\site-packages\lldb\native\_lldb.abi3None" "C:\Program Files\LLVM\Lib\site-packages\lldb\native\_lldb.pyd"

      - name: 🪟 Enable Developer Command Prompt
        if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1.13.0

      - name: 🪟 Use clang-cl
        shell: bash
        if: runner.os == 'Windows'
        run: |
          echo "CC=clang-cl" >> "$GITHUB_ENV"
          echo "CXX=clang-cl" >> "$GITHUB_ENV"

      - name: 🐧 Install LLDB
        if: runner.os == 'Linux'
        run: |
          wget -qO- https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
          sudo add-apt-repository -y 'deb http://apt.llvm.org/noble/ llvm-toolchain-noble-22 main'
          sudo apt update
          sudo apt install lldb-22
          sudo update-alternatives --install /usr/bin/lldb lldb /usr/bin/lldb-22 10
          sudo update-alternatives --install /usr/bin/lldb-server lldb-server /usr/bin/lldb-server-22 10
          lldb --version
          which lldb-server
          readlink -f /usr/bin/lldb-server-22
          which python3
          python3 --version
          PYTHONPATH=`lldb -P` python3 -c 'import lldb'

      - name: 🐧 Use GCC
        if: runner.os == 'Linux' && matrix.compiler == 'gcc'
        run: |
          echo "CC=gcc" >> "$GITHUB_ENV"
          echo "CXX=g++" >> "$GITHUB_ENV"

      - name: 🐧 Use Clang
        if: runner.os == 'Linux' && matrix.compiler == 'clang'
        run: |
          sudo apt install -y --no-install-recommends clang
          echo "CC=clang" >> "$GITHUB_ENV"
          echo "CXX=clang++" >> "$GITHUB_ENV"

      - name: 🍏 Setup Python
        if: runner.os == 'macOS'
        run: |
          export PYTHONPATH=`lldb -P`
          echo "PYTHONPATH=$PYTHONPATH" >> "$GITHUB_ENV"
          echo "$(dirname $(xcrun -f python3))" >> "$GITHUB_PATH"

      - name: Install Qt6
        uses: jurplel/install-qt-action@v4.3.1
        with:
          cache: true
          cache-key-prefix: ${{ runner.os }}-Qt
          version: 6.10.3

      - name: 🪟 Install Python
        uses: actions/setup-python@v6

        if: runner.os == 'Windows'
        with:
          python-version: "3.11" # Matches the python used in LLDB

      - name: Install conan
        run: |
          pip install conan
          conan profile detect -f

      - name: 🪟 Configure
        if: runner.os == 'Windows'
        run: cmake --preset base-test-debug -DCMAKE_COLOR_DIAGNOSTICS=On

      - name: 🐧 Configure
        if: runner.os == 'Linux'
        run: cmake --preset base-test-debug -DCMAKE_COLOR_DIAGNOSTICS=On

      - name: 🍏 Configure
        if: runner.os == 'macOS'
        run: |
          set -x
          unset Python3_ROOT_DIR
          unset Python_ROOT_DIR
          cmake --preset base-test-debug -DCMAKE_COLOR_DIAGNOSTICS=On -DPython3_EXECUTABLE="$(xcrun -f python3)"

      - name: Build
        run: ninja -C build

      - name: Setup tmate session
        if: runner.os == 'macOS' && failure()
        uses: mxschmitt/action-tmate@v3

      - name: Test
        working-directory: build
        run: ctest -j2 --output-on-failure
