name: Test

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
          - os: macos-latest
          - os: ubuntu-latest
            compiler: clang
          - os: ubuntu-latest
            compiler: gcc
    name: 🧪 Test on ${{ matrix.os }}${{case(matrix.compiler == '', '', format(' with {0}', matrix.compiler))}}
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: 🪟/🐧 Install LLVM and Clang
        uses: Nerixyz/install-llvm-action@9360934cdd190acb71725924f8d8ebd7a1acdf93
        if: runner.os == 'Windows' || runner.os == 'Linux'
        with:
          version: "22.1"

      - name: 🪟 🐛 Fix LLDB .pyd
        shell: powershell
        if: runner.os == 'Windows'
        run: |
          mv "C:\Program Files\LLVM\Lib\site-packages\lldb\native\_lldb.abi3None" "C:\Program Files\LLVM\Lib\site-packages\lldb\native\_lldb.pyd"

      - name: 🪟 Enable Developer Command Prompt
        if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1.13.0

      - name: 🪟 Use clang-cl
        shell: bash
        if: runner.os == 'Windows'
        run: |
          echo "CC=clang-cl" >> "$GITHUB_ENV"
          echo "CXX=clang-cl" >> "$GITHUB_ENV"

      - name: 🐧 Install LLDB
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install -y --no-install-recommends lldb

      - name: 🐧 Use GCC
        if: runner.os == 'Linux' && matrix.compiler == 'gcc'
        run: |
          echo "CC=gcc" >> "$GITHUB_ENV"
          echo "CXX=g++" >> "$GITHUB_ENV"

      - name: 🐧 Use Clang
        if: runner.os == 'Linux' && matrix.compiler == 'clang'
        run: |
          sudo apt install -y --no-install-recommends clang
          echo "CC=clang" >> "$GITHUB_ENV"
          echo "CXX=clang++" >> "$GITHUB_ENV"

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@ed7a3b1fda3918c0306d1b724322adc0b8cc0a90 # v1
        with:
          xcode-version: latest

      - name: 🍏 Setup PYTHONPATH
        if: runner.os == 'macOS'
        run: |
          echo "PYTHONPATH=$(lldb -P)" >> "$GITHUB_ENV"

      - name: Install Qt6
        uses: jurplel/install-qt-action@v4.3.1
        with:
          cache: true
          cache-key-prefix: ${{ runner.os }}-Qt
          version: 6.10.3

      - name: 🪟 Install Python
        uses: actions/setup-python@v6

        if: runner.os == 'Windows'
        with:
          python-version: "3.11" # Matches the python used in LLDB

      - name: Install conan
        run: |
          pip install conan
          conan profile detect -f

      - name: Configure
        run: cmake --preset base-test-debug -DCMAKE_COLOR_DIAGNOSTICS=On

      - name: Build
        run: ninja -C build

      - name: Setup tmate session
        if: runner.os == 'macOS'
        uses: mxschmitt/action-tmate@v3

      - name: Test
        working-directory: build
        run: ctest -j2 --output-on-failure
